questions/api/urls.py
from django.conf.urls import url, include
from rest_framework.urlpatterns import format_suffix_patterns
from .views import CreateView, DetailsView
from rest_framework.authtoken import views

urlpatterns = {
    url(r'^auth/', include('rest_framework.urls',
        namespace='rest_framework')), # Adicione esta linha
    url(r'^questions/$', CreateView.as_view(), name="create"),
    url(r'^questions/(?P<pk>[0-9]+)/$',
     DetailsView.as_view(), name="questions_details"),
    url(r'^token/', views.obtain_auth_token),
}

# Adiciona os sufixos de URL aceitos aos nossos urlpatterns.
# Por padrao adiciona html e json.
urlpatterns = format_suffix_patterns(urlpatterns)

questions/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'

urlpatterns = [
    #url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    #url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    #url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    #url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),

    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

questions/questions/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login$', auth_views.login, {'template_name': 'login.html'},
        name='login'),
    url(r'^logout$', auth_views.logout, {'next_page': '/login'},
        name='logout'),
    url(r'^polls/', include('polls.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^admin/', admin.site.urls),
]

questions/api/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

import signals
# Create your models here.

questions/polls/models.py
from __future__ import unicode_literals

from django.db import models
from django import utils
import datetime

from django.contrib.auth.models import User

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    create_date = models.DateTimeField('date created', default=utils.timezone.now)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        return self.pub_date >= utils.timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text.encode('utf-8')

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)

    class Meta:
        permissions = (
            ("user_can_vote", "User can vote on choice"),
        )

    def __str__(self):
        return self.choice_text.encode('utf-8')

class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)

    def __str__(self):
        return ' - '.join([self.user.username, str(self.choice.question),
                       str(self.choice)]).encode('utf-8')

questions/api/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

from rest_framework import generics, permissions
from .permissions import IsAPIUser
from .serializers import QuestionSerializer
from polls.models import Question


class CreateView(generics.ListCreateAPIView):
    queryset = Question.objects.all()
    serializer_class = QuestionSerializer

    def perform_create(self, serializer):
        serializer.save()

class DetailsView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Question.objects.all()
    serializer_class = QuestionSerializer

    permission_classes = (permissions.IsAuthenticated,
                          IsAPIUser)

questions/polls/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.http import HttpResponse
from django.http import Http404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.db.models import F
from django.utils import timezone

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin

from .models import Choice, Question, Vote

class UsersGroupTestMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.groups.filter(name='Users').exists()

class UserCanVoteMixin(PermissionRequiredMixin):
    permission_required = 'polls.can_vote'
    raise_exception = True

class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(pub_date__lte=timezone.now()
                                   ).order_by('-pub_date')[:5]


#class DetailView(UserCanVoteMixin, generic.DetailView):
class DetailView(LoginRequiredMixin, generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

#class ResultsView(UsersGroupTestMixin, generic.DetailView):
class ResultsView(LoginRequiredMixin, generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        vote = Vote(user=request.user, choice=selected_choice)
        vote.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results',
                                            args=(question.id,)))

questions/polls/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}Questions by Codenation Class 1{% endblock %}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'polls/vendor/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for Questions -->
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
  </head>

  <body id="login">

    <div class="container">
      {% if form.errors %}
      <div class="alert alert-danger" role="alert">
          <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
          <span class="sr-only">Error:</span>
          Your username and password didn't match. Please try again.
        </div>
      {% endif %}


      <form class="form-signin" method="post" action="{% url 'login' %}">
        {% csrf_token %}
        <h2 class="form-signin-heading">Questions - Sign in</h2>
        <label for="inputUsername" class="sr-only">Username</label>
        <input type="text" name="username" id="inputUsername" class="form-control" placeholder="Username" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>

    </div> <!-- /container -->
  </body>
</html>

questions/polls/templates/polls/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Questions by Codenation Class 1{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'polls/vendor/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for Questions -->
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

</head>

<body>
    <div class="container">

      <!-- Static navbar -->
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'polls:index' %}">
              <img src="{% static 'polls/img/logo.png' %}" width="140" class="d-inline-block align-top" alt="Codenation">
            </a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="{% url 'polls:index' %}">My Questions</a></li>
              <li><a href="#">Random</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'logout' %}">Logout({{user.username}})</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!-- /.container-fluid -->
      </nav>

      {% block breadcrumb %}
      {% endblock %}

      {% if error_message %}
      <div class="alert alert-danger" role="alert">
          <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
          <span class="sr-only">Error:</span>
          {{ error_message }}
        </div>
      {% endif %}

      {% block content %}{% endblock %}

  </div><!-- container -->

  <script src="{% static 'polls/vendor/jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static 'polls/vendor/bootstrap/dist/js/bootstrap.min.js' %}"></script>
</body>
</html>

questions/polls/templates/polls/detail.html
{% extends "polls/base.html" %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li><a href="{% url 'polls:index' %}">Questions</a></li>
  <li class="active">{{ question.question_text }}</li>
</ol>
{% endblock %}

{% block content %}

     <form action="{% url 'polls:vote' question.id %}" method="post">
     {% csrf_token %}
     <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">{{ question.question_text }}</h3>
      </div>
      <div class="panel-body">
       {% for choice in question.choice_set.all %}
            <div class="radio">
              <label>
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
                {{ choice.choice_text }}
              </label>
            </div>
        {% endfor %}
      </div>
      <div class="panel-footer">
        <input class="btn btn-primary" type="submit" value="Vote" />
      </div>
    </div>
    </form>

{% endblock %}

questions/polls/templates/polls/index.html
{% extends "polls/base.html" %}

{% block content %}

    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">My Questions</h3>
      </div>
      <div class="panel-body">
        {% if latest_question_list %}
        <div class="list-group">
          {% for question in latest_question_list %}
          <a class="list-group-item" href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
          {% endfor %}
        </div>
        {% else %}
            <p>No polls are available.</p>
        {% endif %}
      </div>
    </div>

{% endblock %}

questions/polls/templates/polls/results.html
{% extends "polls/base.html" %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li><a href="{% url 'polls:index' %}">Questions</a></li>
  <li class="active">{{ question.question_text }}</li>
</ol>
{% endblock %}

{% block content %}

     <form action="{% url 'polls:vote' question.id %}" method="post">
     {% csrf_token %}
     <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">{{ question.question_text }}</h3>
      </div>
      <div class="panel-body">
          <ul class="list-group">

          {% for choice in question.choice_set.all %}
            <li class="list-group-item">
                <span class="badge">{{ choice.vote_set.count }}</span>

                {{ choice.choice_text }}
            </li>
          {% endfor %}
          </ul>
      </div>
      <div class="panel-footer">
          <a href="{% url 'polls:detail' question.id %}" class="btn btn-primary" role="button">Vote again?</a>
      </div>
    </div>
    </form>

{% endblock %}